### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by pmp-p** [AGProjects/python-application#1] opened 2016-01-10 17:10 UTC
Hi, 
python setup.py install on version posted https://pypi.python.org/pypi/python-application/2.0.0 :

byte-compiling /usr/local/lib/python2.7/dist-packages/application/python/decorator.py to decorator.pyc

SyntaxError: unqualified exec is not allowed in function 'fix_signature' it is a nested function (decorator.py, line 23)

the same on your trunk.

Btw: your ubuntu trusty repository for sylkserver-webrtc-gateway lacks dependencie python-autobahn (>= 0.10.3)
please announce the only one distrib and architecture you support for sylkserver-webrtc-gateway , it would take _really_ less time to build an qemu/vm than fiddling with obscure dependencies.

**Comment by saghul** [comment] 2016-01-11 08:39
> Hi,
> python setup.py install on version posted https://pypi.python.org/pypi/python-application/2.0.0 :
> 
> byte-compiling /usr/local/lib/python2.7/dist-packages/application/python/decorator.py to decorator.pyc
> 
> SyntaxError: unqualified exec is not allowed in function 'fix_signature' it is a nested function (decorator.py, line 23)
> 
> the same on your trunk.

What exact Python version are you using? I'm not getting this with 2.7.10.

> Btw: your ubuntu trusty repository for sylkserver-webrtc-gateway lacks dependencie python-autobahn (>= 0.10.3)
> please announce the only one distrib and architecture you support for sylkserver-webrtc-gateway , it would take really less time to build an qemu/vm than fiddling with obscure dependencies.

We publish all our dependencies on our Debian repositories. We can also make mistakes. Please open an issue on the corresponding repository.

**Comment by saghul** [comment] 2016-01-11 10:12
Looks like you hit https://bugs.python.org/issue21591, which got fixed in Python 2.7.9. We resorted to using the exec statement and the problem is now gone and version 2.0.1 is released. Thanks for the report!

**Closed as completed by saghul** 2016-01-11 10:12 UTC
